In [18]:
import numpy as np

"""
[start:end:step]
start: inclusive; default=0
end: exclusive; default=len(arr)
step: default = 1

negative values: counting backwards
"""
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6])     # [2, 3, 4, 5, 6]
print(arr[0:7])     # [1, 2, 3, 4, 5, 6, 7]
print(arr[:])       # [1, 2, 3, 4, 5, 6, 7]
print(arr[-1:])     # [7] (because [-1] is inclusive)
print(arr[-3:-1])   # [5, 6] (but -1 here is exclusive)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[7]
[5 6]


7

In [21]:
# steps
print(arr[1:5:2])   # [2, 4] (arr[5] is 6 but exclusive)
print(arr[::2])     # [1, 3, 5, 7] (arr[7] DNE but it's exclusive so we include 7)

[2 4]
[1 3 5 7]


In [23]:
# 2D arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
print(arr[1, 1:4])      # 1 means arr[1], which is [6, 7, 8, 9, 10]
print(arr[0:2, 2])      # From both subarrays, return index 2 (arr[0] to arr[1])
print(arr[0:2, 1:4])    # From both subarrays, slice index 1 to index 4 (not included)

[7 8 9]
[3 8]
