In [53]:
from __future__ import print_function
import torch

In [56]:
x = torch.empty(5, 3)
print(x)

tensor([[0.7554, 0.2125, 0.6454],
        [0.1772, 0.0280, 0.9126],
        [0.9581, 0.3933, 0.4694],
        [0.7131, 0.8033, 0.6217],
        [0.7644, 0.7080, 0.2994]])


In [21]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3251, 0.1956, 0.0232],
        [0.8821, 0.9239, 0.2662],
        [0.8408, 0.3247, 0.0034],
        [0.7454, 0.7741, 0.8065],
        [0.7226, 0.7540, 0.4768]])


In [65]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [67]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [72]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4975, -0.3368,  1.3663],
        [-1.9906,  0.8708,  0.4398],
        [-0.9860, -0.3052, -0.6650],
        [-0.3401, -1.2187,  1.1661],
        [ 1.3197,  2.9246,  0.7626]])


In [73]:
print(x.size())

torch.Size([5, 3])


In [74]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.3066,  0.0237,  2.0983],
        [-1.6779,  1.6503,  0.6121],
        [-0.2384,  0.4653, -0.1179],
        [ 0.2423, -1.2026,  1.4583],
        [ 1.8240,  3.1044,  1.3369]])


In [75]:
print(torch.add(x, y))

tensor([[ 0.3066,  0.0237,  2.0983],
        [-1.6779,  1.6503,  0.6121],
        [-0.2384,  0.4653, -0.1179],
        [ 0.2423, -1.2026,  1.4583],
        [ 1.8240,  3.1044,  1.3369]])


In [76]:
y.add_(x)
print(y)
# inplace operations have _ postfix

tensor([[ 0.3066,  0.0237,  2.0983],
        [-1.6779,  1.6503,  0.6121],
        [-0.2384,  0.4653, -0.1179],
        [ 0.2423, -1.2026,  1.4583],
        [ 1.8240,  3.1044,  1.3369]])


In [78]:
print(x)
print(x[:, 1])

tensor([[-0.4975, -0.3368,  1.3663],
        [-1.9906,  0.8708,  0.4398],
        [-0.9860, -0.3052, -0.6650],
        [-0.3401, -1.2187,  1.1661],
        [ 1.3197,  2.9246,  0.7626]])
tensor([-0.3368,  0.8708, -0.3052, -1.2187,  2.9246])


In [82]:
#resize
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) #size -1 is inferred from other dimensions
print (x, y, z)

tensor([[ 0.3977, -0.9648,  1.8624, -0.4681],
        [ 0.5526, -0.9518, -0.2669,  2.1105],
        [ 0.7599, -0.7547, -0.0928,  2.2084],
        [ 2.0956,  0.7505,  0.1542,  1.7928]]) tensor([ 0.3977, -0.9648,  1.8624, -0.4681,  0.5526, -0.9518, -0.2669,  2.1105,
         0.7599, -0.7547, -0.0928,  2.2084,  2.0956,  0.7505,  0.1542,  1.7928]) tensor([[ 0.3977, -0.9648,  1.8624, -0.4681,  0.5526, -0.9518, -0.2669,  2.1105],
        [ 0.7599, -0.7547, -0.0928,  2.2084,  2.0956,  0.7505,  0.1542,  1.7928]])


In [85]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2274])
-0.22740697860717773


In [87]:
#tensor to numpy array
a = torch.ones(5)
print (a)
b = a.numpy()
print (b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [88]:
a.add_(1)
print(a)
print(b)
# numpy array changed in value
# same reference?

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [91]:
# numpy array to tensor

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

# np.add(a, 1, out=a)
a = np.add(a, 1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [93]:
# cuda tensors
#let this cell run only if cuda is available
# torch.device is used to move tensors in and out of GPU
print(x)

if torch.cuda.is_available():
    dvce = torch.device("cuda")
    y = torch.ones_like(x, device=dvce)
    x = x.to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.2274], device='cuda:0')
tensor([0.7726], device='cuda:0')
tensor([0.7726], dtype=torch.float64)
